# Generated by Django 4.0.2 on 2022-02-27 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='module_instance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ratings.moduleinstance'),
            preserve_default=False,
        ),
    ]
