# Generated by Django 4.0.2 on 2022-02-28 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_ratings_module_instance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='submitting_user',
        ),
    ]
